### ISSUE TITLE
plugin install error messge: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by wlugmayr** [scipion-em/scipion-em-chimera#110]
Updated scipion to v3.5 and started to update the plugins.

The plugin seems to work in an existing project and starts chimerax 1.6.1 but during install the following happens:

>scipion-em->scipion-em-chimera==3.4.0) (2024.2.2)
This method will return the plugin class in the future. Please use getPluginModule instead
Traceback (most recent call last):
  File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/scipion/install/plugin_funcs.py", line 334, in getInstallenv
    plugin.defineBinaries(env)
  File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/chimera/__init__.py", line 115, in defineBinaries
    tmpFile.write(f"devel install {pathToPlugin}")
  File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/tempfile.py", line 489, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
Scipion v3.5.0 - Eugenius
Error retrieving plugin ChimeraX binaries:  a bytes-like object is required, not 'str'
Installing scipion-em-chimera ...
/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/bin/python -m pip install scipion-em-chimera==3.4.0
Done (1.92 seconds)
Couldn't get binaries definition of ChimeraX plugin: a bytes-like object is required, not 'str'
Installing chimerax-1.6.1 ...
  All targets exist, skipping.
Done (0.00 seconds)

**Comment by azazellochg** [comment]
This has been fixed in devel: https://github.com/scipion-em/scipion-em-chimera/commit/bccc72b4de922da4841124afea2cf2cd53f260b2
Update: now fixed in production as well
