### ISSUE TITLE
chimerax tests failing in Scipion 3.0.5 

### ISSUE THREAD

**Issue by jasonkey** [scipion-em/scipion-em-chimera#43]
Hi SCIPION developers, 

I'm having trouble with ChimeraX in SCIPION 3. I installed scipion-em-chimera and it appeared to install normally and without any errors. I did approve the UCSF license and confirm that ChimeraX actually works, AFAICT. 

A few of the scipion3 ChimeraX tests pass, but most fail with some variation of the `scipionwrite #3 prefix DONOTSAVESESSION_` error message below. 

ChimeraX appears to behave normally - GUI runs, basic functions work. 
Is this a bug or an installation issue on my end? 

Thanks - 
Jason

```
>>> ERROR running protocol chimera fit
pdb and volume
 save volume and model
    FAILED with error: Protocol failed: Command '/programs/x86_64-linux/scipion/3.0.0/software/em/chimerax-1.1/bin/ChimeraX  --nogui /zpool_haumea/data/key/ScipionUserData/projects/TestChimeraFit
2/Runs/000090_ChimeraProtRigidFit/tmp/chimeraScript.cxc' returned non-zero exit status 70.


*************** LAST 50 LINES OF THE LOG *********************

INFO:
Fit molecule 1ake_start.pdb (#3) to map import_1ake_4-5A.mrc (#2) using 1656 atoms
  average map value = 0.6059, steps = 68
  shifted from previous position = 2.49
  rotated from previous position = 0.111 degrees
  atoms outside contour = 1155, contour level = 0.74446

INFO:
Position of 1ake_start.pdb (#3) relative to import_1ake_4-5A.mrc (#2) coordinates:
  Matrix rotation and translation
     0.99999902  -0.00112069   0.00083366 -25.48205428
     0.00111956   0.99999846   0.00135084 -45.40153070
    -0.00083517  -0.00134991   0.99999874 -26.53395202
  Axis  -0.69506982   0.42949330   0.57655308
  Axis point   0.00000000 -12384.82802080 28163.20334135
  Rotation angle (degrees)   0.11131396
  Shift along axis -17.08607818

STATUS:
68 steps, shift 2.49, rotation 0.111 degrees, average map value 0.6059
ERROR:
scipionwrite #3 prefix DONOTSAVESESSION_
ERROR:
Unknown command: scipionwrite #3 prefix DONOTSAVESESSION_
0.00% done: Initializing core
50.00% done: Initializing bundles
100.00% done: Finished initialization
** Running command: /programs/x86_64-linux/scipion/3.0.0/software/em/chimerax-1.1/bin/ChimeraX  --nogui /zpool_haumea/data/key/ScipionUserData/projects/TestChimeraFit2/Runs/000090_ChimeraProtRigi
dFit/tmp/chimeraScript.cxc
Traceback (most recent call last):
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 188, in run
    self._run()
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 239, in _run
    resultFiles = self._runFunc()
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 235, in _runFunc
    return self._func(*self._args)
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/chimera/protocols/protocol_base.py", line 292, in runChimeraStep
    Chimera.runProgram(Plugin.getProgram(), args, cwd=cwd)
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pwem/viewers/viewer_chimera.py", line 116, in runProgram
    pwutils.runJob(None, prog, args, env=cls.getEnviron(),
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 53, in runJob
    return runCommand(command, env, cwd)
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 68, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/programs/x86_64-linux/scipion/3.0.0/scipion_extlib/python-3.8.6-jhyh/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/programs/x86_64-linux/scipion/3.0.0/software/em/chimerax-1.1/bin/ChimeraX  --nogui /zpool_haumea/data/key/ScipionUserData/projects/TestChimeraFit2/Runs/000090
_ChimeraProtRigidFit/tmp/chimeraScript.cxc' returned non-zero exit status 70.
Protocol failed: Command '/programs/x86_64-linux/scipion/3.0.0/software/em/chimerax-1.1/bin/ChimeraX  --nogui /zpool_haumea/data/key/ScipionUserData/projects/TestChimeraFit2/Runs/000090_ChimeraPr
otRigidFit/tmp/chimeraScript.cxc' returned non-zero exit status 70.
FAILED: runChimeraStep, step 2, time 2020-10-16 08:36:22.133531
*** Last status is failed
------------------- PROTOCOL FAILED (DONE 2/3)

*************** END OF THE LOG *********************
```

**Comment by pconesa** [comment]
Thanks @jasonkey for the report.

Scipion needs a ChimeraX plugin to be installed. scipion-em-chimera should have installed it, since is the default behavior`.

Let's check the status of it:

` scipion3 installb | grep scipionchimera`

I'm getting this:

scipionchimera           1.0     [X]    

If there is not an X, try to install it like:  `scipion3 installb scipionchimera`

 
What happens if you open ChimeraX like:

`/programs/x86_64-linux/scipion/3.0.0/software/em/chimerax-1.1/bin/ChimeraX`

and then, in the command prompt type:

`help scipionwrite`

**Comment by jasonkey** [comment]
Hi Pablo, 

The scipionchimera box is checked in my installb output, though the `scipionchimera-1.0` directory in `software/em` is empty 

If I remove this empty directory and run a `scipion3 installb scipionchimera`, it appears to succeed : 

```
 $ ./scipion3 installb scipionchimera
Scipion v3.0.5 () devel
Building scipionchimera-1.0 ...
  Skipping command: wget -nv -c -O /programs/x86_64-linux/scipion/3.0.0/software/em/void.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/em/void.tgz
mv -v /programs/x86_64-linux/scipion/3.0.0/software/em/void.tgz.part /programs/x86_64-linux/scipion/3.0.0/software/em/void.tgz
  All targets exist.
cd /programs/x86_64-linux/scipion/3.0.0/software/em
mkdir /programs/x86_64-linux/scipion/3.0.0/software/em/scipionchimera-1.0
  Skipping command: tar -xf void.tgz -C scipionchimera-1.0
  All targets exist.
cd /programs/x86_64-linux/scipion/3.0.0/software/em/scipionchimera-1.0
/programs/x86_64-linux/scipion/3.0.0/software/em/chimerax-1.1/bin/ChimeraX --nogui --exit --cmd 'devel install /programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/chimera/Bundles/scipion'
0.00% done: Initializing core
50.00% done: Initializing bundles
Executing: devel install /programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/chimera/Bundles/scipion
running build
running build_py
running bdist_wheel
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/chimerax
creating build/bdist.linux-x86_64/wheel/chimerax/scipionExtensions
copying build/lib/chimerax/scipionExtensions/__init__.py -> build/bdist.linux-x86_64/wheel/chimerax/scipionExtensions
creating build/bdist.linux-x86_64/wheel/chimerax/scipionExtensions/docs
creating build/bdist.linux-x86_64/wheel/chimerax/scipionExtensions/docs/user
creating build/bdist.linux-x86_64/wheel/chimerax/scipionExtensions/docs/user/commands
copying build/lib/chimerax/scipionExtensions/docs/user/commands/scipionss.html -> build/bdist.linux-x86_64/wheel/chimerax/scipionExtensions/docs/user/commands
copying build/lib/chimerax/scipionExtensions/docs/user/commands/scipionwrite.html -> build/bdist.linux-x86_64/wheel/chimerax/scipionExtensions/docs/user/commands
copying build/lib/chimerax/scipionExtensions/docs/user/commands/scipionrs.html -> build/bdist.linux-x86_64/wheel/chimerax/scipionExtensions/docs/user/commands
copying build/lib/chimerax/scipionExtensions/cmd.py -> build/bdist.linux-x86_64/wheel/chimerax/scipionExtensions
running install_egg_info
running egg_info
writing ChimeraX_ScipionExtensions.egg-info/PKG-INFO
writing dependency_links to ChimeraX_ScipionExtensions.egg-info/dependency_links.txt
writing requirements to ChimeraX_ScipionExtensions.egg-info/requires.txt
writing top-level names to ChimeraX_ScipionExtensions.egg-info/top_level.txt
reading manifest file 'ChimeraX_ScipionExtensions.egg-info/SOURCES.txt'
writing manifest file 'ChimeraX_ScipionExtensions.egg-info/SOURCES.txt'
Copying ChimeraX_ScipionExtensions.egg-info to build/bdist.linux-x86_64/wheel/ChimeraX_ScipionExtensions-1.2-py3.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/ChimeraX_ScipionExtensions-1.2.dist-info/WHEEL
creating 'dist/ChimeraX_ScipionExtensions-1.2-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'chimerax/scipionExtensions/__init__.py'
adding 'chimerax/scipionExtensions/cmd.py'
adding 'chimerax/scipionExtensions/docs/user/commands/scipionrs.html'
adding 'chimerax/scipionExtensions/docs/user/commands/scipionss.html'
adding 'chimerax/scipionExtensions/docs/user/commands/scipionwrite.html'
adding 'ChimeraX_ScipionExtensions-1.2.dist-info/METADATA'
adding 'ChimeraX_ScipionExtensions-1.2.dist-info/WHEEL'
adding 'ChimeraX_ScipionExtensions-1.2.dist-info/top_level.txt'
adding 'ChimeraX_ScipionExtensions-1.2.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Distribution is in /programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/chimera/Bundles/scipion/dist/ChimeraX_ScipionExtensions-1.2-py3-none-any.whl
Executing: toolshed install /programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/chimera/Bundles/scipion/dist/ChimeraX_ScipionExtensions-1.2-py3-none-any.whl reinstall true
Successfully installed ChimeraX-ScipionExtensions-1.2
Installed ChimeraX-ScipionExtensions (1.2)

100.00% done: Finished initialization
UCSF ChimeraX version: 1.1 (2020-09-09)
© 2016-2020 Regents of the University of California.  All rights reserved.
  Skipping command: Link 'scipionchimera-1.0 -> scipionchimera-1.0'
  All targets exist.
Done (8.44 seconds)
```

but `software/em/scipionchimera-1.0` directory is still empty and the `help scipionwrite` command in ChimeraX produces `No help found for 'scipionwrite'` as the output. The files appear to go into the scipion env in  .scipion3env/lib/python3.8/site-packages/chimera . Maybe I can force it to load with a PYTHONPATH variable, or maybe a symlink in ChimeraX ?

**Comment by pconesa** [comment]
The folder empty is fine, is just a file system flag to tell scipion the
plugin was installed. All goes into chimerax folder, and seems to install
correctly. Not sure what is happening.

**Comment by jasonkey** [comment]
I think I figured it out - 

This command is failing : 
`Executing: toolshed install /programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/chimera/Bundles/scipion/dist/ChimeraX_ScipionExtensions-1.2-py3-none-any.whl reinstall true`
but it is not obvious from the output during installation.

If I run the command manually with 
`ChimeraX --toolshed install /programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/chimera/Bundles/scipion/dist/ChimeraX_ScipionExtensions-1.2-py3-none-any.whl`
The program starts but crashes without installing anything. 

If I run 
`.../chimerax-1.1/bin/python3.7 -m pip install /programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/chimera/Bundles/scipion/dist/ChimeraX_ScipionExtensions-1.2-py3-none-any.whl`

The install works, `help scipionwrite` works from the command line in the ChimeraX GUI and the Chimera tests pass in scipion3.  I'm not sure if I'm missing anything by going this route vs using the toolshed method.

**Comment by pconesa** [comment]
Nice! Thanks Jason.

Is this a ChimeraX issue?

**Comment by rmarabini** [comment]
Hi @jasonkey 

   It is a bit late but I think the problem is that the extensions of chimera developed by scipion have not been properly installed.

   Open chimerax and execute


devel install /path_to_scipion_plugins/scipion-em-chimera/chimera/Bundles/scipion

 close chimerax.

Hopefully it will work


          Roberto

**Comment by jasonkey** [comment]
Thanks Roberto - I'll give that a try. 

Installing directly with the ChimeraX pip and whl file seems to have worked. 
The issue appears to be a ChimeraX crash with the `--toolshed install` flag. I tried to strace and debug it, but I didn't get very far.

It would be nice to enable command line installation wherever possible, or let users know when a GUI is required. For example, I ran into issues with ChimeraX because of the license approval. That requires a GUI and fails silently if there isn't one. Maybe license approval and installation of ChimeraX extensions is possible without graphical components ?

For now, nearly all my scipion3 tests are passing and things look good - thanks for the help

**Comment by pconesa** [comment]
Hi @jasonkey , We were asked to remove any installation of chimera as we were doing before due to licensing terms. They were very serious with these. 

So all we could do is to actually load their download pages from an "embedded ultra basic browser". So the actions in "Our" gui are actually request to their server. This way I do not think we are breaking any law.

I guess a no GUI mode could be implemented, but not sure about how legal it is, providing we keep the site requests.

**Comment by rmarabini** [comment]
I do nor know if this issue has been solved. since it has been inactive for 2 weeks I close it but we may reopen it if needed.

**Comment by jasonkey** [comment]
Yep - we're solved for now. Thanks
Installation of the ChimeraX_ScipionExtensions whl works using the pip provided in ChimeraX
